version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: kgi
      RABBITMQ_DEFAULT_PASS: kgi
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kgi
      POSTGRES_PASSWORD: kgi
